/**
 * Easebuzz Payment Gateway Utility
 * Handles the initiation of the checkout overlay with proper callbacks.
 */

declare global {
    interface Window {
        EasebuzzCheckout: any;
    }
}

/**
 * Initiates the Easebuzz checkout overlay.
 * @param key Your Merchant Key (Public)
 * @param accessKey The access_key generated by the Easebuzz API via your Cloud Function
 * @param onResponse Callback fired when the payment completes or fails
 * @param env 'test' for sandbox, 'prod' for live
 */
export const initiateEasebuzzCheckout = (
    key: string,
    accessKey: string,
    onResponse: (response: any) => void,
    env: 'test' | 'prod' = 'prod'
): void => {
    if (!window.EasebuzzCheckout) {
        console.error("Easebuzz SDK not loaded. Ensure the script is added to index.html");
        return;
    }

    const easebuzzCheckout = new window.EasebuzzCheckout(key, env);

    easebuzzCheckout.initiatePayment({
        access_key: accessKey,
        onResponse: (response: any) => {
            console.log("Easebuzz Response:", response);
            onResponse(response);
        },
        theme: "#5227ff"
    });
};

/**
 * Helper to generate a unique transaction ID
 */
export const generateTxnId = (prefix: string = "AVR"): string => {
    return `${prefix}_${Date.now()}_${Math.random().toString(36).substr(2, 5).toUpperCase()}`;
};
